version: "3"
services: 
    node:
        build: ./nodejs
        container_name: nodejs
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node ./src/index.js
        tty: true
        volumes:
            - ./nodejs:/usr/app/src
        ports:
            - "3000:3000"
        networks:
            - nodenet
    
    nginx:
        build: ./nginx
        container_name: nginx
        networks:
            - nodenet
        ports:
            - "8080:80"
        depends_on:
            - node

    db:
        image: mysql:5.7
        container_name: db
        command: "--innodb_use_native_aio=0"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - nodenet
        tty: true
        restart: always

networks:
  nodenet:
    driver: bridge
